version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: midterm
    ports:
      - "5432:5432"
    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
    driver: local

