version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: midterm
    ports:
      - "5432:5432"
    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
#  shop-online:
#    image: postgres:latest
#    container_name: shop-online
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 123
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL81Dialect
#      APP_SECRET_KEY: thisIsSecretKey

volumes:
  postgres_data:
    driver: local
#  shop_online_data:
#    driver: local

